[tool.poetry]
name = "pyphy"
version = "0.1.0"
description = ""
authors = ["Tobia Ochsner <tobia.ochsner@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
attrs = "^25.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
